Update p10k
To https://github.com/romkatv/powerlevel10k/commit/1e7be00e04a6e34bdcc7574297413fd6a48be51f

diff --git a/zsh/zdotdir/powerlevel10k/gitstatus/build b/zsh/zdotdir/powerlevel10k/gitstatus/build
--- a/zsh/zdotdir/powerlevel10k/gitstatus/build
+++ b/zsh/zdotdir/powerlevel10k/gitstatus/build
@@ -55,7 +55,7 @@ workdir="$(command pwd)"
 
 narg() { echo $#; }
 
-if [ "$(narg $workdir)" != 1 -o -z "${workdir##*:*}" ]; then
+if [ "$(narg $workdir)" != 1 -o -z "${workdir##*:*}" -o -z "${workdir##*=*}" ]; then
   >&2 echo "[error] cannot build in this directory: $workdir"
   exit 1
 fi
@@ -90,6 +90,9 @@ if [ -n "$gitstatus_install_tools" ]; then
     freebsd)
       command pkg install -y cmake gmake binutils gcc git perl5
     ;;
+    openbsd)
+      command pkg_add install cmake gmake gcc git wget
+    ;;
     netbsd)
       command pkgin -y install cmake gmake binutils git
     ;;
@@ -102,7 +105,7 @@ if [ -n "$gitstatus_install_tools" ]; then
         sudo port -N install libiconv cmake wget
       elif command -v brew >/dev/null 2>&1; then
         for formula in libiconv cmake git wget; do
-          if command brew list "$formula" &>/dev/null; then
+          if command brew ls --version "$formula" &>/dev/null; then
             command brew upgrade "$formula"
           else
             command brew install "$formula"
@@ -135,6 +138,14 @@ esac
 
 cflags="$archflag=$gitstatus_cpu -fno-plt"
 
+command touch "$workdir"/file-prefix-map-test.c
+if 2>/dev/null "${CC:-/bin/cc}"           \
+     -ffile-prefix-map=x=y                \
+     -c "$workdir"/file-prefix-map-test.c \
+     -o "$workdir"/file-prefix-map-test.o; then
+  cflags="$cflags -ffile-prefix-map=$workdir/="
+fi
+
 if [ "$gitstatus_cpu" = x86-64 ]; then
   cflags="$cflags -mtune=generic"
 fi
@@ -155,6 +166,13 @@ case "$gitstatus_kernel" in
     libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   freebsd)
+    gitstatus_make=gmake
+    gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
+  ;;
+  openbsd)
+    gitstatus_cxx=eg++
     gitstatus_make=gmake
     gitstatus_ldflags="$gitstatus_ldflags -static"
     gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
@@ -306,16 +324,33 @@ app="$outdir"/usrbin/"$appname"
 command strip "$app".tmp
 
 command mkdir -- "$workdir"/repo
-command git -C "$workdir"/repo init
-command git -C "$workdir"/repo config user.name "Your Name"
-command git -C "$workdir"/repo config user.email "you@example.com"
-command git -C "$workdir"/repo commit --allow-empty --allow-empty-message --no-gpg-sign -m ''
+printf '[init]\n  defaultBranch = master\n' >"$workdir"/.gitconfig
+(
+  cd -- "$workdir"/repo
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git init
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git config user.name "Your Name"
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git config user.email "you@example.com"
+  GIT_CONFIG_NOSYSTEM=1 HOME="$workdir" command git commit \
+    --allow-empty --allow-empty-message --no-gpg-sign -m ''
+)
 
 resp="$(printf "hello\037$workdir/repo\036" | "$app".tmp)"
-[ -n "$resp" -a -z "${resp##hello*1*$workdir/repo*master*}" ]
+case "$resp" in
+  hello*1*/repo*master*);;
+  *)
+    >&2 echo 'error: invalid gitstatusd response for a git repo'
+    exit 1
+  ;;
+esac
 
 resp="$(printf 'hello\037\036' | "$app".tmp)"
-[ -n "$resp" -a -z "${resp##hello*0*}" ]
+case "$resp" in
+  hello*0*);;
+  *)
+    >&2 echo 'error: invalid gitstatusd response for a non-repo'
+    exit 1
+  ;;
+esac
 
 command mv -f -- "$app".tmp "$app"
 
@@ -423,13 +458,16 @@ fi
 
 if [ -z "$gitstatus_cpu" ]; then
   case "$gitstatus_arch" in
-    armv6l)         gitstatus_cpu=armv6;;
+    armel)          gitstatus_cpu=armv5;;
+    armv6l|armhf)   gitstatus_cpu=armv6;;
     armv7l)         gitstatus_cpu=armv7;;
     arm64)          gitstatus_cpu=armv8;;
     aarch64)        gitstatus_cpu=armv8-a;;
     ppc64le)        gitstatus_cpu=powerpc64le;;
     riscv64)        gitstatus_cpu=rv64imafdc;;
     x86_64|amd64)   gitstatus_cpu=x86-64;;
+    x86)            gitstatus_cpu=i586;;
+    s390x)          gitstatus_cpu=z900;;
     i386|i586|i686) gitstatus_cpu="$gitstatus_arch";;
     *)
       >&2 echo '[error] unable to infer target CPU architecture'
@@ -458,12 +496,13 @@ case "$gitstatus_kernel" in
       fi
       if [ -z "$docker_image" ]; then
         case "$gitstatus_arch" in
-          x86_64)         docker_image=alpine:3.11.6;;
-          i386|i586|i686) docker_image=i386/alpine:3.11.6;;
-          armv6l)         docker_image=arm32v6/alpine:3.11.6;;
-          armv7l)         docker_image=arm32v7/alpine:3.11.6;;
-          aarch64)        docker_image=arm64v8/alpine:3.11.6;;
-          ppc64le)        docker_image=ppc64le/alpine:3.11.6;;
+          x86_64)             docker_image=alpine:3.11.6;;
+          x86|i386|i586|i686) docker_image=i386/alpine:3.11.6;;
+          armv6l|armhf)       docker_image=arm32v6/alpine:3.11.6;;
+          armv7l)             docker_image=arm32v7/alpine:3.11.6;;
+          aarch64)            docker_image=arm64v8/alpine:3.11.6;;
+          ppc64le)            docker_image=ppc64le/alpine:3.11.6;;
+          s390x)              docker_image=s390x/alpine:3.11.6;;
           *)
             >&2 echo '[error] unable to infer docker image'
             >&2 echo 'Please specify explicitly with `-i IMAGE`.'
@@ -473,7 +512,7 @@ case "$gitstatus_kernel" in
       fi
     fi
   ;;
-  freebsd|netbsd|darwin)
+  freebsd|openbsd|netbsd|darwin)
     if [ -n "$docker_cmd" ]; then
       >&2 echo "[error] docker (-d) is not supported on $gitstatus_kernel"
       exit 1
